### ISSUE TITLE
오탈자 제보드려요

### ISSUE THREAD

**Issue by 00parkjihye** [Jeonghun-Ban/TIL#5]
<img width="210" alt="오탈자" src="https://user-images.githubusercontent.com/75290488/102042658-bbbea180-3e15-11eb-8526-3844287707ef.png">

TIL>HTML5>Introduction.md
중간쯤에 HTML5의 기능 아래에 있는
[ HTML5'이' 전체 기능 > HTML5'의' 전체 기능 ]  오탈자 인 것 같아 제보드려요

**Comment by junghoon-vans** [comment]
제보 감사드립니다.
해당 부분 수정 완료했습니다! [(0e61a35)](https://github.com/Jeonghun-Ban/TIL/commit/0e61a359377bbc4ff3aa8fdb2dbc2812b98c609b)
